### ISSUE TITLE
After update to 1.5.1 device tab and map tab are empty

### ISSUE THREAD

**Issue by BigDi** [ioBroker/ioBroker.zigbee#1062]
The adapter is working but config is not view / editable.
I had the followed error in log
`
starting. Version 1.5.1 in /opt/iobroker/node_modules/iobroker.zigbee, node: v10.19.0, js-controller: 3.2.16
....
zigbee.1 | 2021-04-18 14:39:54.488 | error | at adapter.getEnumsAsync.then.then.then.then (/opt/iobroker/node_modules/iobroker.zigbee/lib/commands.js:174:28)
-- | -- | -- | --
zigbee.1 | 2021-04-18 14:39:54.488 | error | at Array.forEach (<anonymous>)
zigbee.1 | 2021-04-18 14:39:54.488 | error | at result.forEach (/opt/iobroker/node_modules/iobroker.zigbee/lib/commands.js:196:32)
zigbee.1 | 2021-04-18 14:39:54.488 | error | at Array.map (<anonymous>)
zigbee.1 | 2021-04-18 14:39:54.488 | error | at devInfo.statesDef.filter.map (/opt/iobroker/node_modules/iobroker.zigbee/lib/commands.js:202:48)
zigbee.1 | 2021-04-18 14:39:54.488 | error | (10250) getDevices error: TypeError: name.replace is not a function

`

**Comment by asgothian** [comment]
Please check issue #1059

A.

**Comment by BigDi** [comment]
I didn't make any changes like in issue 1059 is discussed. I added the code row and get the followed output after restart and open the map
`
zigbee.1 (9026) getDevices error: TypeError: name.replace is not a function
at devInfo.statesDef.filter.map (/opt/iobroker/node_modules/iobroker.zigbee/lib/commands.js:203:48)
at Array.map ()
at result.forEach (/opt/iobroker/node_modules/iobroker.zigbee/lib/commands.js:196:32)
at Array.forEach ()
at adapter.getEnumsAsync.then.then.then.then (/opt/iobroker/node_modules/iobroker.zigbee/lib/commands.js:174:28)`

**Comment by asgothian** [comment]
- The entry has no connection to the devices adapter.
- The log line is the same as you posted before. Please also post the last 10 info messages you receive from the zigbee adapter before and after the error message
A.

**Comment by BigDi** [comment]
I delete the whole device from last log output. Now the map is working! Thank you.
