### ISSUE TITLE
After Update from 1.4.5 to 1.5.1 missing information at device tab and device map

### ISSUE THREAD

**Issue by dp20eic** [ioBroker/ioBroker.zigbee#1059]
Hi,
after update from 1.4.5 -> 1.5.1 I do not see any picture at the device tab and the device map is also empty.

From device tab:
![image](https://user-images.githubusercontent.com/71387331/115040816-1f470180-9ed2-11eb-998d-68dc35406bb1.png)

From device map:
![image](https://user-images.githubusercontent.com/71387331/115040909-38e84900-9ed2-11eb-9f9e-bda3eeab4dad.png)

I get the following "error" message:
```
zigbee.0	2021-04-16 16:50:11.105	error	at /opt/iobroker/node_modules/iobroker.zigbee/lib/commands.js:174:28
zigbee.0	2021-04-16 16:50:11.105	error	at Array.forEach (<anonymous>)
zigbee.0	2021-04-16 16:50:11.105	error	at /opt/iobroker/node_modules/iobroker.zigbee/lib/commands.js:196:32
zigbee.0	2021-04-16 16:50:11.105	error	at Array.map (<anonymous>)
zigbee.0	2021-04-16 16:50:11.105	error	at /opt/iobroker/node_modules/iobroker.zigbee/lib/commands.js:202:48
zigbee.0	2021-04-16 16:50:11.105	error	(6643) getDevices error: TypeError: name.replace is not a function
```

**Comment by asgothian** [comment]
Please check your object tree. You seem to have a device where the name has been deleted.

A.

**Comment by kirovilya** [comment]
hmm... **common.name** is object...
@dp20eic try to put this code line
`this.info(JSON.stringify(stateDef.common.name));`
before [line 197](https://github.com/ioBroker/ioBroker.zigbee/blob/master/lib/commands.js#L197) in lib/commands.js file, restart adapter and show logs

**Comment by dp20eic** [comment]
@kirovilya, @asgothian
I check at the object tree all entrys and I remove my changes I did, as in example shown.

`
84182600000aa57a | OG_Arbeitszimmer [Decke Licht 03] | device |   |   |   |   | editdelete
-- | -- | -- | -- | -- | -- | -- | --
available | OG_Arbeitszimmer [Available] | state | state |   |   | true | editdeletebuild
brightness | OG_Arbeitszimmer [Brightness] | state | level.dimmer |   |   | 100 | editdeletebuild
brightness_move | OG_Arbeitszimmer [Dimming] | state | state |   |   |   | editdeletebuild
colortemp | OG_Arbeitszimmer [Color temperature] | state | level.color.temperature |   |   | 153 | editdeletebuild
device_query | OG_Arbeitszimmer [Trigger device query] | state | button |   |   | room_service | editdeletebuild
groups | OG_Arbeitszimmer [Groups] | state | state |   |   | ["11"] | editdeletebuild
link_quality | OG_Arbeitszimmer [Link quality] | state | state |   |   | 54 | editdeletebuild
state | OG_Arbeitszimmer [Switch state] | state | switch |   |   | false | editdeletebuild
transition_time | OG_Arbeitszimmer [Transition time] | state | state |   |   | 0 sec
`
Befor Version 1.5.x it was no Problem. But as I check and remove all additional changes I saw that I have "}" instate of "]" in one or two devices.

I close the issue, now the devices are back at dasboard and the tiles are working too.

Thank's for your help.
