### ISSUE TITLE
mixin-deep module not found

### ISSUE THREAD

**Issue by MiWoBln** [ioBroker/ioBroker.zigbee#1078]
after Update to 1.5.3 starting of zigbee failed.

 node:internal/modules/cjs/loader:927
   throw err;
   ^
 Error: Cannot find module 'mixin-deep'
 Require stack:
 - /opt/iobroker/node_modules/zigbee-herdsman/dist/controller/controller.js
 - /opt/iobroker/node_modules/zigbee-herdsman/dist/index.js
 - /opt/iobroker/node_modules/zigbee-herdsman-converters/converters/toZigbee.js
 - /opt/iobroker/node_modules/zigbee-herdsman-converters/index.js
 - /opt/iobroker/node_modules/iobroker.zigbee/lib/utils.js
 - /opt/iobroker/node_modules/iobroker.zigbee/lib/commands.js
 - /opt/iobroker/node_modules/iobroker.zigbee/main.js
     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
     at Function.Module._load (node:internal/modules/cjs/loader:769:27)
     at Module.require (node:internal/modules/cjs/loader:996:19)
     at require (node:internal/modules/cjs/helpers:92:18)
     at Object.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/controller.js:48:38)
     at Module._compile (node:internal/modules/cjs/loader:1092:14)
     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
     at Module.load (node:internal/modules/cjs/loader:972:32)
     at Function.Module._load (node:internal/modules/cjs/loader:813:14)
     at Module.require (node:internal/modules/cjs/loader:996:19) {
   code: 'MODULE_NOT_FOUND',
   requireStack: [
     '/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/controller.js',
     '/opt/iobroker/node_modules/zigbee-herdsman/dist/index.js',
     '/opt/iobroker/node_modules/zigbee-herdsman-converters/converters/toZigbee.js',
     '/opt/iobroker/node_modules/zigbee-herdsman-converters/index.js',
     '/opt/iobroker/node_modules/iobroker.zigbee/lib/utils.js',
     '/opt/iobroker/node_modules/iobroker.zigbee/lib/commands.js',
     '/opt/iobroker/node_modules/iobroker.zigbee/main.js'
   ]
 }
instance system.adapter.zigbee.0 terminated with code 1 (JS_CONTROLLER_STOPPED)

**Comment by arteck** [comment]
check now .. install from GIT

**Comment by asgothian** [comment]
Fixed in 1.5.5
