### ISSUE TITLE
restart loop due to new group feature + Gledopto Controller

### ISSUE THREAD

**Issue by MichaelKorn** [ioBroker/ioBroker.zigbee#2640]
### describe the problem in Detail. What do you expect to happen ? What does happen ?

Hello,

I'm using Zigbee with groups and after updating to 3.1.5 I got the following issues:
This new line https://github.com/ioBroker/ioBroker.zigbee/blob/master/lib/groups.js#L632 is causing in combination with https://github.com/Koenkk/zigbee-herdsman-converters/blob/v25.31.0/src/devices/gledopto.ts#L549 a restart loop.
Seems like a `device` is expect as argument, which is not provided.

Thanks,
Michael

### Adapter version

3.1.5

### Coordinator firmware version

20210708

### Coordinator

Sonoff_Zigbee_3.0_USB_Dongle_Plus

### Setup

Intel NUC

### Protocol of the error (as text, encapsulated in multiline code tags <>). Separate different occurrances into clearly split log sections

```
error	device.getEndpoint is not a function
error	TypeError: device.getEndpoint is not a function at Object.endpoint (/opt/iobroker/node_modules/zigbee-herdsman-converters/dist/devices/gledopto.js:556:24) at Groups.syncGroups (/opt/iobroker/node_modules/iobroker.zigbee/lib/groups.js:632:55)
error	unhandled promise rejection: device.getEndpoint is not a function
error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
```

**Comment by asgothian** [comment]
Please test with the current 3.2.0 RC  from here (GitHub install)

https://github.com/ioBroker/ioBroker.zigbee/tarball/3.2.0rc

A.

**Comment by MichaelKorn** [comment]
Thanks A.,

I got the same error again and I looked into the code.
The zigbee-herdsman `device` is encapsulated in a data structure specific to ioBroker.zigbee. (https://github.com/ioBroker/ioBroker.zigbee/blob/master/lib/zigbeecontroller.js#L690)
You need to pass `entity.device` (not just `entity`).
Already test, it works.

Best,
Michael

**Comment by asgothian** [comment]
thanks, I'll update the code to rely on that. As I didnt have any devices which require this, I was unable to test it completely.

A.

**Comment by asgothian** [comment]
Should be fixed in the current latest version (3.2.1)
