### ISSUE TITLE
After Upgrade to 1.5.6  - Error: Cannot find module 'mz'

### ISSUE THREAD

**Issue by SneakyV** [ioBroker/ioBroker.zigbee#1153]
Hello!

Can someone give me a tip on how to install the "mz" module?

Here is the error message:

host.ioBroker | 2021-07-10 16:49:02.203 | error | instance system.adapter.zigbee.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.ioBroker | 2021-07-10 16:49:02.203 | error | Caught by controller[0]: }
host.ioBroker | 2021-07-10 16:49:02.202 | error | Caught by controller[0]: ]
host.ioBroker | 2021-07-10 16:49:02.202 | error | Caught by controller[0]: '/opt/iobroker/node_modules/iobroker.zigbee/main.js'
host.ioBroker | 2021-07-10 16:49:02.202 | error | Caught by controller[0]: '/opt/iobroker/node_modules/iobroker.zigbee/lib/seriallist.js',
host.ioBroker | 2021-07-10 16:49:02.202 | error | Caught by controller[0]: '/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/serialPortUtils.js',
host.ioBroker | 2021-07-10 16:49:02.202 | error | Caught by controller[0]: '/opt/iobroker/node_modules/zigbee-herdsman/dist/utils/index.js',
host.ioBroker | 2021-07-10 16:49:02.202 | error | Caught by controller[0]: '/opt/iobroker/node_modules/zigbee-herdsman/dist/utils/backup.js',
host.ioBroker | 2021-07-10 16:49:02.202 | error | Caught by controller[0]: requireStack: [
host.ioBroker | 2021-07-10 16:49:02.202 | error | Caught by controller[0]: code: 'MODULE_NOT_FOUND',
host.ioBroker | 2021-07-10 16:49:02.201 | error | Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:974:19) {
host.ioBroker | 2021-07-10 16:49:02.201 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:790:14)
host.ioBroker | 2021-07-10 16:49:02.201 | error | Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:950:32)
host.ioBroker | 2021-07-10 16:49:02.201 | error | Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
host.ioBroker | 2021-07-10 16:49:02.201 | error | Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:1085:14)
host.ioBroker | 2021-07-10 16:49:02.201 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/zigbee-herdsman/dist/utils/backup.js:34:14)
host.ioBroker | 2021-07-10 16:49:02.201 | error | Caught by controller[0]: at require (internal/modules/cjs/helpers.js:92:18)
host.ioBroker | 2021-07-10 16:49:02.201 | error | Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:974:19)
host.ioBroker | 2021-07-10 16:49:02.200 | error | Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:746:27)
host.ioBroker | 2021-07-10 16:49:02.200 | error | Caught by controller[0]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
host.ioBroker | 2021-07-10 16:49:02.200 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.zigbee/main.js
host.ioBroker | 2021-07-10 16:49:02.200 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.zigbee/lib/seriallist.js
host.ioBroker | 2021-07-10 16:49:02.200 | error | Caught by controller[0]: - /opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/serialPortUtils.js
host.ioBroker | 2021-07-10 16:49:02.200 | error | Caught by controller[0]: - /opt/iobroker/node_modules/zigbee-herdsman/dist/utils/index.js
host.ioBroker | 2021-07-10 16:49:02.200 | error | Caught by controller[0]: - /opt/iobroker/node_modules/zigbee-herdsman/dist/utils/backup.js
host.ioBroker | 2021-07-10 16:49:02.200 | error | Caught by controller[0]: Require stack:
host.ioBroker | 2021-07-10 16:49:02.200 | error | Caught by controller[0]: Error: Cannot find module 'mz'
host.ioBroker | 2021-07-10 16:49:02.199 | error | Caught by controller[0]: ^
host.ioBroker | 2021-07-10 16:49:02.199 | error | Caught by controller[0]: throw err;
host.ioBroker | 2021-07-10 16:49:02.199 | error | Caught by controller[0]: internal/modules/cjs/loader.js:905
host.ioBroker | 2021-07-10 16:49:01.839 | info | instance system.adapter.zigbee.0 started with pid 14857
host.ioBroker | 2021-07-10 16:48:31.827 | info | Restart adapter system.adapter.zigbee.0 because enabled

**Comment by SneakyV** [comment]
Okay, I have now managed to reinstall all the missing modules after the update.
Unfortunately, this happens far too often that nothing works after an update :-(
